spring:
  config:
    activate:
      on-profile: "prod"

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy:
          # 추가 예정
    show-sql: true
    properties:
      hibernate:
        format_sql: true
